import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient()
async function main() {
  const newCharacter = await prisma.character.create({
    data: {
      // Character Information
      race: 'Human',
      profession: 'Warrior',
      level: 1,
      experience: 0,
      characterName: 'John Doe',
      equipment: 'Basic Sword',
      magic: 'None',
      settings: 'Default',
      realmpower: 10,
      powerpoints: 5,
      basehp: 100,
      totalhp: 100,
      actualhp: 100,
      attributes: 'Basic Attributes',
      temporaryAbbr: 'Temp',
      potentialAbbr: 'Pot',
      developmentAbbr: 'Dev',
      baseAbbr: 'Base',
      raceAbbr: 'Race',
      totalAbbr: 'Total',
      constitution: 10,
      agility: 10,
      selfdiscipline: 10,
      memory: 10,
      reasoning: 10,
      strength: 10,
      quickness: 10,
      presence: 10,
      empathy: 10,
      intuition: 10,
      defenses: 'Basic Defenses',
      armorAt: 'Leather',
      defensivebonusDb: 'Basic',
      withshield: 'No',
      movementpenalty: 'None',
      helmet: 'None',
      armgreaves: 'None',
      leggreaves: 'None',
      distancepenalty: 'None',
      wounds: 'None',
      languages: 'Common',
      spoken: 'Common',
      writen: 'Common',
      miscellaneous: 'None',
      hitdice: '1d6',
      developmentpoints: 10,
      primaryskills: 'Basic Skills',
      attributemodAbbr: 'AttrMod',
      cost: 0,
      professionAbbr: 'Prof',
      nbranks: 1,
      attributeAbbr: 'Attr',
      miscellaneousAbbr: 'Misc',
      itemAbbr: 'Item',
      secondaryskills: 'None',
      weaponskills: 'Basic Weapon Skills',
      ob: 10,
      db: 5,
      resistances: 'Basic Resistances',
      notes: 'None',
      weight: 70,
      possessions: 'None',
      mithril: 0,
      gold: 10,
      silver: 20,
      bronze: 30,
      copper: 40,
      iron: 50,
      spelllists: 'None',
      realm: 'None',
      listtype: 'None',
      levelmax: 1,
      learnchances: 0,
      bookandpage: 'None',
      spellname: 'None',
      spellclass: 'None',
      spellduration: 'None',
      spellrange: 'None',
      description: 'None',
      relations: 'None',
      constitutioncheck: 10,
      agilitycheck: 10,
      selfdisciplinecheck: 10,
      memorycheck: 10,
      reasoningcheck: 10,
      strengthcheck: 10,
      quicknesscheck: 10,
      presencecheck: 10,
      empathycheck: 10,
      intuitioncheck: 10,
      resistancecheck: 10,
      ennemydb: 5,
      result: 'None',
      devAbbr: 'Dev',
      loadcapacity: 100,
      weighttotal: 70,
      sheetColors: 'Default',
      totalhpcalcmode: 'Default',
      legacycalc: 'None',
      nocalc: 'None',
      hpcalcdescription: 'None',
      professionbonusmode: 'Default',
      legacyprofbonus: 'None',
      flatprofbonus: 'None',
      profbonusmodedescription: 'None',
      bmr: 10,
      walk: 5,
      fastwalk: 10,
      run: 15,
      sprint: 20,
      accsprint: 25,
      dash: 30,
      skilldevmode: 'Default',
      legacyskilldev: 'None',
      flatskilldev: 'None',
      skilldevmodedescription: 'None',
      secundarydevelopmentpoints: 5,
      secondaryskilldevmode: 'Default',
      bonus10: 10,
      bonus20: 20,
      bonus25: 25,
      bonus30: 30,
      bonus40: 40,
      bonus50: 50,
      secondaryskilldevmodedescription: 'None',
      backgroundColor: 'White',
      default: 'Default',
      white: 'White',
      lilac: 'Lilac',
      grayscale: 'Grayscale',
      book: 'Book',
      seasonSummer: 'Summer',
      seasonFall: 'Fall',
      seasonWinter: 'Winter',
      seasonSpring: 'Spring',
      backgroundcolordesc: 'Default',
      createdBy: 'createdBy', // replace with actual value
      updatedBy: 'updatedBy', // replace with actual value
    },
  })

  console.log({ newCharacter })
}
main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
